server:
  port: 8080
  ssl:
    enabled: true
    key-store: classpath:keystore/baeldung.p12
    key-store-password: password
    key-store-type: PKCS12
    key-alias: baeldung
spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true