CREATE TABLE broadcast
(
    broadcast_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255),
    description  VARCHAR(255),
    started_at   TIMESTAMP,
    ended_at     TIMESTAMP,
    created_at   TIMESTAMP,
    modified_at  TIMESTAMP,
    status       VARCHAR(50),
    viewer_count INT
);
