/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.example.api_meta

import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.runApplication

@SpringBootApplication
class ApiMetaApplication

fun main(args: Array<String>) {
    runApplication<ApiMetaApplication>(*args)
}
