server:
  port: 8081
  ssl:
    enabled: true
    key-store: classpath:keystore/baeldung.p12
    key-store-password: password
    key-store-type: PKCS12
    key-alias: baeldung
spring:
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
  profiles:
    active: local # default profile
---
spring:
  config:
    activate:
      on-profile: local
host: # org.example.api_signaling.properties.HostProperties
  signaling: 'wss://localhost:8081'
  meta: 'https://localhost:8080'

---
spring:
  config:
    activate:
      on-profile: cloud
host: # org.example.api_signaling.properties.HostProperties
  signaling: 'wss://5jyo.site'
  meta: 'https://5jyo.site'
