server:
  port: 8081
  ssl:
    enabled: true
    key-store: classpath:keystore/baeldung.p12
    key-store-password: password
    key-store-type: PKCS12
    key-alias: baeldung
spring:
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
