server:
  port: 8081
  ssl:
    enabled: false
    key-store: classpath:keystore/baeldung.p12
    key-store-password: password
    key-store-type: PKCS12
    key-alias: baeldung
spring:
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
  profiles:
    active: local # default profile
---
spring:
  config:
    activate:
      on-profile: local
host: # org.example.api_signaling.properties.HostProperties
  signaling: 'ws://localhost:8081'
  meta: 'http://localhost:8080'

---
spring:
  config:
    activate:
      on-profile: cloud
host: # org.example.api_signaling.properties.HostProperties
  signaling: wss://5jyo.site # TODO: [HOST] Set to AWS domain
  meta: https://5jyo.site # TODO: [HOST] Set to AWS domain